name: Daily AI Research Report
on:
  schedule:
    # 每天北京时间上午9点执行 (UTC时间凌晨1点)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发
    inputs:
      force_run:
        description: '强制执行任务'
        required: false
        default: 'false'

jobs:
  send-daily-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: 发送每日AI研究报告
      run: |
        echo "开始执行每日AI研究报告任务..."
        
        # 调用管理后台API执行每日任务
        response=$(curl -s -w "%{http_code}" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -d '{"action": "daily_task"}' \
          "${{ secrets.SITE_URL }}/api/daily-task" \
          -o response.json)
        
        http_code="${response: -3}"
        
        if [ "$http_code" -eq 200 ]; then
          echo "✅ 每日任务执行成功"
          cat response.json
        else
          echo "❌ 每日任务执行失败，HTTP状态码: $http_code"
          cat response.json
          exit 1
        fi
    
    - name: 通知执行结果
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "🎉 AI研究日报发送成功！"
        else
          echo "⚠️ AI研究日报发送失败，请检查日志"
        fi
