name: Test GitHub Actions Runner

on:
  push:
    branches:
      - main
      - master
      - Jules-branch-for-testing-the-github-actions-is-working-or-not

jobs:
  test-runner-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a success message
        run: echo "✅ The GitHub Actions runner is working on this repository."
